apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mlflow-role
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: mlflow
    app.kubernetes.io/instance: mlflow
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups: [""]
  resources: ["deployments", "pods"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mlflow-rb
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: mlflow
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: mlflow-role
  apiGroup: rbac.authorization.k8s.io