kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: mlflow
  labels:
    app.kubernetes.io/instance: mlflow
    app.kubernetes.io/name: mlflow
spec:
  to:
    kind: Service
    name: mlflow-proxy
    weight: 100
  port:
    targetPort: proxy
  tls:
    termination: reencrypt