apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlflow
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"mlflow"{{ "}}" }}'
  labels:
    app.kubernetes.io/name: mlflow
    app.kubernetes.io/instance: mlflow
